<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_userid</name>
   <tag></tag>
   <elementGuidId>1d0eed6e-7cc3-4c3c-99f0-4bc04192cc24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc45ae00-05d0-49b8-ba6e-b33c9beb9258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>3b12e8d0-f18f-4623-bcf6-231c152b2449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userid</value>
      <webElementGuid>7882dcca-3df9-4539-8f02-599b17c78993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>User ID</value>
      <webElementGuid>9f1d5e4b-dd75-4737-97d6-a8b8f8862b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>6265f7d3-9ae5-4aaa-82e9-f991be6b77f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>570841c7-1ccd-4043-a832-f8958b4dbe9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User ID</value>
      <webElementGuid>fa02f203-68ba-4313-b195-6a87c9ae3cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b666d76-9e20-4044-a4dd-4d6981843b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>c5cb9fe6-83d4-4545-b0a7-af572220444c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userid&quot;)</value>
      <webElementGuid>6c303d3f-5b7c-43a0-81bc-eb83b542063b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userid']</value>
      <webElementGuid>4bb6860c-ee86-4db9-ae6d-2a1681b93cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Login']/input</value>
      <webElementGuid>f5f101bf-a54b-4f59-926a-c4d7b80b8ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a4d8bd69-76d8-4888-b216-64171b1b0f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'userid' and @id = 'userid' and @type = 'text' and @placeholder = 'User ID']</value>
      <webElementGuid>0296b6a6-84bc-4204-9738-ed9b6cda057a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
