<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate Internet Usage Policy_button</name>
   <tag></tag>
   <elementGuidId>94307631-c5b3-4955-ad7b-e29f35f03727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56c15a75-b48a-494a-b0e9-0fac2bb9414c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0c1d5e07-4d1d-400e-bc16-ec0203f4ec7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95fe6c82-ca38-40b2-9f32-290fe02ac589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I Accept</value>
      <webElementGuid>cc4b8eb0-4830-4684-9d67-5ca41e954733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>5c598ca1-a722-4c5a-9a39-db3c5e2154d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pg gr&quot;]/div[@class=&quot;pg_cont&quot;]/form[1]/table[@class=&quot;m_tbl&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;table-upper&quot;]/tbody[1]/tr[4]/td[@class=&quot;eu_co&quot;]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>41e6cd6e-a9f3-4e60-81af-0c1dd57003fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='button']</value>
      <webElementGuid>580a1356-0007-4790-97f4-1d2b8fe39f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>87b27c0a-2686-4c84-9f02-f325065f4bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'button']</value>
      <webElementGuid>f458642a-4703-49b2-837d-f9fad114bab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
