<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>895fa75d-6da2-4956-92c6-c291b82e2a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc21dd05-7230-4afc-9644-16de0d063bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>3929e773-6278-4389-9b0c-6eb00d69ac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>3653ea3f-897b-4c7e-83f9-66f2e97cd318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.disabled=true;document.body.style.cursor = 'wait'; this.className='formButton-disabled';form.submit();return false;</value>
      <webElementGuid>4f04ca07-2749-4039-8027-b89afb93d8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Confirm</value>
      <webElementGuid>bf17231f-6e0d-43af-93da-ff16342b9878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Confirm&quot;)</value>
      <webElementGuid>219f9222-d5e8-46ef-9d1c-b2f14d19fca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Confirm']</value>
      <webElementGuid>7b4ba2f5-e4f7-449b-9175-e3b1ea8a7640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logoutConsent']/div/div/div/button</value>
      <webElementGuid>07be307c-e99c-4fdf-826c-a20d800b348e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm your Single Sign-Off action'])[1]/following::button[1]</value>
      <webElementGuid>604c3150-7439-4206-b634-4c224d3674bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout Consent'])[1]/following::button[1]</value>
      <webElementGuid>5a44c1f7-a36e-486c-80d0-72cafb0995c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Confirm', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>ff3e7756-29e9-4da4-b9e2-82d320cf3fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>95bba07d-fe34-49b5-bb5c-d1c1b09b6e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>605f07f7-9a65-478d-985c-ee6071fe9810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Confirm' and @name = 'Confirm' and (text() = ' Confirm' or . = ' Confirm')]</value>
      <webElementGuid>6e922d39-7c24-4e43-a467-d7314cdeddc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
