<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CreateAbsenceType__FOpt1_FOr10_FONSr20MAn_32819f</name>
   <tag></tag>
   <elementGuidId>cca09034-4ff9-4999-b924-f6b9a835eb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec0b3a72-aff3-49cd-ba32-c163d600f601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>428b5ce2-ec11-4435-af8a-efedb3a5aecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xdv</value>
      <webElementGuid>54c247f2-6397-40c3-9c96-00826e145328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::btn</value>
      <webElementGuid>b7e95b97-5212-4207-98a7-6cf2f8f87f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::btn&quot;)</value>
      <webElementGuid>4f1b351a-5b71-4e6e-8b36-9d69d5541670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::btn']</value>
      <webElementGuid>59c30140-276f-4b7d-b37c-c254ade98b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::cntnr']/a</value>
      <webElementGuid>6b97ff05-b7b7-45a1-9013-d5dbe85fe26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/a</value>
      <webElementGuid>e59374bd-7dde-4295-8a91-1f09f539d725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:typSis:typSrh::btn']</value>
      <webElementGuid>dc0f3ea1-29f4-49fe-b050-3d794999b8f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
