<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_15</name>
   <tag></tag>
   <elementGuidId>5ed7c922-21bc-45f6-9ad0-af82cb888de0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:bsDtPce:abDtsT:0:abSt1Dt::pop::cd::cg']/tbody/tr[4]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fca7534f-f38e-43c1-b83e-ecfd83eaac2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>74b948eb-7c17-4029-a99f-b5a3d652dae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>de0fbf52-4b9f-4071-8812-783ce7704e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x12i</value>
      <webElementGuid>daa2e7ad-1fe3-414f-8023-2b3fcd9bbb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-afr-adfday</name>
      <type>Main</type>
      <value>cm</value>
      <webElementGuid>4b0aba4d-54dd-43d6-bcf9-b6bd83383af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>91a566ff-7b2c-4c99-9abb-a4556aae7e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:bsDtPce:abDtsT:0:abSt1Dt::pop::cd::cg&quot;)/tbody[1]/tr[@class=&quot;x12b&quot;]/td[@class=&quot;x12i&quot;]</value>
      <webElementGuid>b2542b89-b90f-450b-830a-9779a56ae5d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:bsDtPce:abDtsT:0:abSt1Dt::pop::cd::cg']/tbody/tr[4]/td[4]</value>
      <webElementGuid>dd636127-57cd-4da5-b3de-8b0bde8d2cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[18]</value>
      <webElementGuid>f552b603-7782-412b-975a-cf9365fb0405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::td[18]</value>
      <webElementGuid>56b0ec8d-16d2-478e-8cc8-5b0b9925cd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::td[33]</value>
      <webElementGuid>59df669a-6c26-48ed-9a05-a7bbc4c4145d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/preceding::td[46]</value>
      <webElementGuid>89779b60-84fa-4199-904c-8ded12d3b465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>3f77b894-0fd5-4579-bc08-1ac228da0414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]</value>
      <webElementGuid>a748286e-6e1a-4b1f-90f0-920d1cb4584c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '15' or . = '15')]</value>
      <webElementGuid>15894f27-a9b9-48e7-990c-ae046fe9c4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
