<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments__FOpt1_FOr10_FONSr20MAnt2_af6923</name>
   <tag></tag>
   <elementGuidId>7fdd0a13-8de8-4513-bf03-1ff801a9a44c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp::content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5c843a7d-17c0-45f1-a930-ed5c7ce2197f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp::content</value>
      <webElementGuid>f343c156-cbba-4ac3-8fd3-a21a69c77723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp</value>
      <webElementGuid>50b69e06-4f49-4360-84c5-7f334b6a5f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x25</value>
      <webElementGuid>9729a116-8b8d-4b86-827e-9e74e9292f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d35e6fc5-9b83-4c81-a4f4-48e47d365396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f85a39dd-2e5b-4cec-988b-ea7ee9b952b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6edf2a52-914f-4f37-8ab0-e5bc1a582731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp::content&quot;)</value>
      <webElementGuid>02c45420-4f0d-4c7e-85c5-499a20e60b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp::content']</value>
      <webElementGuid>2a5d1a17-8e06-4b4e-a29d-ff46db89e785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp']/div[2]/textarea</value>
      <webElementGuid>8ea9bdfc-acf8-4a64-a7e9-b584433ee054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ed72f934-0ccb-4715-9970-87f8bc2db868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp::content' and @name = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:adAbUpl:UPsp1:cmtAtSh:cmntInp']</value>
      <webElementGuid>1cf8547a-4ba1-47ab-8dda-a20e9cc053cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
