<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Absence</name>
   <tag></tag>
   <elementGuidId>d327df77-19cb-4e48-8306-f64169d748be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='quickaction'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>163d7a66-c670-4b0a-9327-39c2ad2f54b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>me_add_absence</value>
      <webElementGuid>d9007324-640d-4960-a290-9f4b5ae3d912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-nav-label flat-grid-nav-label flat-quickactions-item-link</value>
      <webElementGuid>5c736d93-4224-4613-9324-81ec137b875a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>quickaction</value>
      <webElementGuid>8929015a-d4c4-4aa6-afc1-c820d39c13c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>groupNode_my_information</value>
      <webElementGuid>75d3cd72-c2b3-4128-b857-06bac94d3a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>quickactioncategory</name>
      <type>Main</type>
      <value>grp_me_absences</value>
      <webElementGuid>c5996943-057d-4802-95cd-d07a4544daab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3f9808bc-4971-4eb8-8893-8a110bad569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Absence</value>
      <webElementGuid>ff47b881-19eb-4998-a2af-4d248a848c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickactions_groupNode_my_information&quot;)/div[@class=&quot;flat-quickactions-container&quot;]/div[1]/a[@class=&quot;app-nav-label flat-grid-nav-label flat-quickactions-item-link&quot;]</value>
      <webElementGuid>b65e1d04-b7b6-4294-8e16-c655e2418ca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='quickaction'])[15]</value>
      <webElementGuid>623f67fd-371a-49b1-b336-dcb4d35d26ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quickactions_groupNode_my_information']/div[15]/div/a</value>
      <webElementGuid>0ffeb825-81e5-4ce9-ac56-3fbb5d8e8582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Absence')]</value>
      <webElementGuid>215d2e60-adb8-44ad-8ae3-489a4df81ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Actions'])[1]/following::a[15]</value>
      <webElementGuid>f1b0bf39-ff78-46d8-9380-66feaee322ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good afternoon, sugguna Bk!'])[1]/following::a[17]</value>
      <webElementGuid>cd788d3e-5ca9-4441-95ba-131a7d931502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/preceding::a[6]</value>
      <webElementGuid>5dffb507-108d-48c1-a6db-d20524bd341d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Things to Finish'])[1]/preceding::a[26]</value>
      <webElementGuid>95d5120d-1bee-481d-a746-18a70fccbe15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Absence']/parent::*</value>
      <webElementGuid>82fc6c63-e0d5-4716-a468-b64396bc7ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[27]</value>
      <webElementGuid>72f30f5b-a998-4817-8f6e-5cb9926eea5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/a</value>
      <webElementGuid>9c457bb2-cc8d-4ede-a79a-f3f7bda257a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'quickaction' and @href = '#' and (text() = 'Add Absence' or . = 'Add Absence')]</value>
      <webElementGuid>7cc345fa-5fc8-4850-a405-f81c3c5e9830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
