<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Existing Absences</name>
   <tag></tag>
   <elementGuidId>d40e6c8a-b6fd-4395-8804-3b2e891f600c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@type='quickaction'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec70815b-98d0-4845-af58-c5dc06d5c497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>me_existing_absences</value>
      <webElementGuid>58ac17e0-006b-4749-979d-1ebd12ed203c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-nav-label flat-grid-nav-label flat-quickactions-item-link</value>
      <webElementGuid>b3e9955f-70cb-4230-b027-712f2973375e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>quickaction</value>
      <webElementGuid>541c3d47-22e7-4805-a908-436d1e35f2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>groupNode_my_information</value>
      <webElementGuid>29d3c94f-85df-4608-940c-c747be9fd304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>quickactioncategory</name>
      <type>Main</type>
      <value>groupNode_frequently_used_quick_actions</value>
      <webElementGuid>505d9fc0-0af9-4bb9-a888-901163ef801f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>133c4499-b0ab-4ed5-a222-cd6b440064e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Existing Absences</value>
      <webElementGuid>145a92b2-5416-44c2-bc2f-cb848eeaf556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickactions_groupNode_my_information&quot;)/div[@class=&quot;flat-quickactions-container&quot;]/div[1]/a[@class=&quot;app-nav-label flat-grid-nav-label flat-quickactions-item-link&quot;]</value>
      <webElementGuid>042dcb2e-a205-4331-8903-53342fd97cc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='quickaction'])[3]</value>
      <webElementGuid>421cc0e7-8535-4ca1-a84f-edf5671e7b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quickactions_groupNode_my_information']/div[3]/div/a</value>
      <webElementGuid>459d9317-808c-44f4-bbab-cdb13611f54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Existing Absences')]</value>
      <webElementGuid>a7f8b862-e22a-4c34-85b0-4073d996f77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Actions'])[1]/following::a[3]</value>
      <webElementGuid>04d6a5dd-c6b3-4a7d-aa05-ea6e2e75b5f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good afternoon, sugguna Bk!'])[1]/following::a[5]</value>
      <webElementGuid>f84607dd-f4d5-4ebb-b785-991006898506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps'])[1]/preceding::a[18]</value>
      <webElementGuid>b53e04d5-84fb-4195-a2f3-a25fc1bfe149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Things to Finish'])[1]/preceding::a[38]</value>
      <webElementGuid>e9b8c066-5564-4f70-a5f1-57cfa464e753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Existing Absences']/parent::*</value>
      <webElementGuid>ce1f86a5-0e1f-4595-97d9-6df2bc8fe95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>2f551616-ea55-4f68-ada7-b21d6bfa4318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>208d9618-3eba-453b-96ec-03ea136d074b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'quickaction' and @href = '#' and (text() = 'Existing Absences' or . = 'Existing Absences')]</value>
      <webElementGuid>a1e4dfd9-8138-4804-bf34-a57169f96425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
