<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dismiss</name>
   <tag></tag>
   <elementGuidId>4a08c7b3-63a4-4277-9d61-e376bccd89e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pt1:_UISatr:0:lv4:0:cb4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cfebaf1-6361-4392-ae02-8f414ac69d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_UISatr:0:lv4:0:cb4</value>
      <webElementGuid>f105c1c9-c15f-4c78-92ae-512cfc57cb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget homebutton-secondary x7j p_AFTextOnly</value>
      <webElementGuid>7d534190-af49-4d54-9fbf-d154b652ed73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false;</value>
      <webElementGuid>4b98f059-8807-497a-bfae-6e39639dac33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Clear</value>
      <webElementGuid>8cd5ac92-e705-4e52-aa47-e49b9191f3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>1c809436-c8bd-4d16-a722-d79441d6c3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UISatr:0:lv4:0:cb4&quot;)</value>
      <webElementGuid>62b400d4-413b-4f18-8181-9a0d891cd861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pt1:_UISatr:0:lv4:0:cb4']</value>
      <webElementGuid>1c8f34d1-daa4-4a4d-bd47-301e56fab086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pt1:_UISatr:0:lv4:0:pgl7']/tbody/tr/td[2]/button</value>
      <webElementGuid>9a9db191-750d-4cfd-aa94-58f457859adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sugguna Bk'])[3]/following::button[1]</value>
      <webElementGuid>5db596bf-9afe-48b9-ae82-c8d5d15bf6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FYI'])[2]/following::button[1]</value>
      <webElementGuid>dd463f69-8f44-4a8a-80e8-3fdc5ef02a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved'])[2]/preceding::button[1]</value>
      <webElementGuid>f62371a9-d834-4b11-b008-0bf9e7629066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sugguna Bk'])[4]/preceding::button[1]</value>
      <webElementGuid>92a94b1b-6e1e-4168-8d28-2731c348ad67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/button</value>
      <webElementGuid>3977540f-bb58-488f-99ab-9d84f5a6fd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pt1:_UISatr:0:lv4:0:cb4' and @title = 'Clear' and (text() = 'Dismiss' or . = 'Dismiss')]</value>
      <webElementGuid>f6f9aa6a-ae1a-4381-afc6-4fab2387fa44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
