<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading_pt1_UIScmil2u</name>
   <tag></tag>
   <elementGuidId>3d870c1d-cf7c-4797-8ba4-1e62473f7247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pt1:_UIScmil2u']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df871bee-6493-4b8b-bcea-d2a154740046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_UIScmil2u</value>
      <webElementGuid>a51fa46f-cc4e-404a-9909-859022a2192e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Settings and Actions</value>
      <webElementGuid>97b6a750-fba8-41a4-a93b-365c6035c890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Settings and Actions</value>
      <webElementGuid>ecf87985-dbbf-49ef-8f85-a338bd510b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget xjd</value>
      <webElementGuid>cf13b3c7-7a01-4a0a-99b6-6846c8c1fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fa-erwh-test-saasfaprod1.fa.ocs.oraclecloud.com:443/hcmUI/personImage?personId=300000134331512&amp;returnSquare=true&amp;maxSize=80&amp;returnInitials=Y</value>
      <webElementGuid>22ecddec-810b-4c92-83d7-2d1d4f85e4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UIScmil2u&quot;)</value>
      <webElementGuid>8f8e4b85-2d9c-4255-81bd-7d645e58e430</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pt1:_UIScmil2u']</value>
      <webElementGuid>cae1164b-b388-4cd4-ad2b-8fea646f1a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_UISpb1::content']/img</value>
      <webElementGuid>feb38486-edf2-4579-bfb0-6616e9bc2d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Settings and Actions']</value>
      <webElementGuid>01ffe394-bf10-45d1-88e6-557b6b25cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/table/tbody/tr/td/div/div/div/img</value>
      <webElementGuid>09541b63-4cd5-4f49-bf27-cf0675696a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pt1:_UIScmil2u' and @title = 'Settings and Actions' and @alt = 'Settings and Actions' and @src = 'https://fa-erwh-test-saasfaprod1.fa.ocs.oraclecloud.com:443/hcmUI/personImage?personId=300000134331512&amp;returnSquare=true&amp;maxSize=80&amp;returnInitials=Y']</value>
      <webElementGuid>e3b27a4d-ac60-42c5-9739-f1711c901c67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
