<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Welcome, sugguna Bk_pt1_UIScil1u</name>
   <tag></tag>
   <elementGuidId>0d569e6b-4515-4a69-abe1-24852d696a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_UIScil1u']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2714dfb2-7cb3-433e-a058-0bdba93e0d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_UIScil1u</value>
      <webElementGuid>7ed4d276-c877-4be8-9154-2d22bee77dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Oracle Logo Home</value>
      <webElementGuid>668745b6-a23c-46c3-bf5b-a462510d5003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget xn0 xko p_AFTextOnly</value>
      <webElementGuid>0d8ede3a-c103-4762-be86-804afa4d669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>this.focus();return false;</value>
      <webElementGuid>30738d96-018b-4615-9125-6d0abb748cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d6896d39-5c6f-4492-b1f9-9b46ff89d0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UIScil1u&quot;)</value>
      <webElementGuid>3c6fc02b-ee96-490a-a561-8a0e03d422a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pt1:_UIScil1u']</value>
      <webElementGuid>dca648f5-2a37-4e8f-b483-d0b1d6fbe9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='pt1:_UISpg4']/tbody/tr/td[3]/a</value>
      <webElementGuid>b93b8815-fd63-42a5-8b70-7442ebf1221e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>d810c5d4-ad87-4be5-83bc-469b87554f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>6ed9c44f-6dc4-4251-bd54-2fcf26464fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pt1:_UIScil1u' and @title = 'Oracle Logo Home' and @href = '#']</value>
      <webElementGuid>90f2362b-7393-41a9-a6de-68c232f4223e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
