<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome, sugguna Bk_pt1image8</name>
   <tag></tag>
   <elementGuidId>34eb4c4f-a004-41e9-a11f-ce2b05089bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pt1:image8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dc545595-ebbc-43b3-beae-e394dc1a7529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:image8</value>
      <webElementGuid>8ceb24df-8eae-40ec-810d-5fc85d3857db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>927e5e23-28a0-43e8-8aab-a5522266f34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>8e57d059-0593-404a-bfb2-4e9f2589220e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget xjd</value>
      <webElementGuid>0bc7f895-a066-42c6-b966-56801214df91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/fscmUI/images/qual_home_78_achr.png</value>
      <webElementGuid>5c16fd31-5428-4a6d-a84d-68ff633dcb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:image8&quot;)</value>
      <webElementGuid>06a3d693-91c4-4d3a-8335-079a45ede16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pt1:image8']</value>
      <webElementGuid>9617ba4c-2ab2-44c7-924a-bff642cb436b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:panelGroupLayout42']/div/img</value>
      <webElementGuid>2f92b79e-bcaa-4e5f-9418-314094a9ee6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Home']</value>
      <webElementGuid>72732822-fdb9-45fa-a246-c1992825f226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/img</value>
      <webElementGuid>e9dc0b71-ea07-4243-a5c4-385b195e4d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'pt1:image8' and @title = 'Home' and @alt = 'Home' and @src = '/fscmUI/images/qual_home_78_achr.png']</value>
      <webElementGuid>f17cdb6e-4200-4678-b026-045960a5b852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
