<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate Internet Usage Policy_button</name>
   <tag></tag>
   <elementGuidId>fae3e6e9-9d6f-4ae9-8f6b-d232ab905974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88b2e93a-529e-48a0-a387-540435e7ac10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b086822f-dc30-447c-ad9c-8b886f098c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5fd3b39-4685-4345-a670-e8ad77d7a856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I Accept</value>
      <webElementGuid>445923a4-f718-4bda-bb2e-b7070b9ec226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>97b679d1-e93e-4c6e-8a2d-8a79d30a05ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;pg gr&quot;]/div[@class=&quot;pg_cont&quot;]/form[1]/table[@class=&quot;m_tbl&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;table-upper&quot;]/tbody[1]/tr[4]/td[@class=&quot;eu_co&quot;]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;btn&quot;]</value>
      <webElementGuid>ccc3ff62-811b-4650-a0e9-00a405d5fe93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='button']</value>
      <webElementGuid>06f89529-4600-4b57-8bba-452cfbd8dd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[2]</value>
      <webElementGuid>c546d561-7711-42a7-9e64-b3d872b4fe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'button']</value>
      <webElementGuid>08769121-d73a-4aac-899b-87c7d0082b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
