<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Scheduled__FOpt1_FOr10_FONSr20MAnt20r10_1d250d</name>
   <tag></tag>
   <elementGuidId>d6d7e6dd-90d3-4734-9019-8de50dab31c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil::icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7752f09d-5129-418a-9801-78d8a681489b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil::icon</value>
      <webElementGuid>394e915f-143f-46a6-973e-6f04f309ba17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/hcmUI/images/applcore/fuseplus/patterns/func_pencil_16_hov.png</value>
      <webElementGuid>aeea8b42-e5b4-42dd-9ec4-595ee5673f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Absence Type Bereavement Leave Hours 8  Start Date 13-04-2023 End Date 13-04-2023 Status Scheduled Edit</value>
      <webElementGuid>c73efe6d-0a61-41f5-80ad-aac703b16ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value> Absence Type Bereavement Leave Hours 8  Start Date 13-04-2023 End Date 13-04-2023 Status Scheduled Edit</value>
      <webElementGuid>18d973eb-48ff-459e-b93e-235ddfe02194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xi6</value>
      <webElementGuid>7e904285-29a6-4c32-b342-23efb9f22b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil::icon&quot;)</value>
      <webElementGuid>cf47eaf1-228f-48c5-9c4b-c4da34cd7b3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil::icon']</value>
      <webElementGuid>66e8a555-7f4d-4aa4-a4cc-14984161f3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil']/img</value>
      <webElementGuid>fa13f7fd-f025-4496-92e1-bc1b94075f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' Absence Type Bereavement Leave Hours 8  Start Date 13-04-2023 End Date 13-04-2023 Status Scheduled Edit']</value>
      <webElementGuid>ac7f9a4c-c485-4005-a15f-b91ec64da337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>584b3fc9-665d-41cc-b9f0-561a696ae81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:hisPce:abHisLv:0:hisPse:penCil::icon' and @src = '/hcmUI/images/applcore/fuseplus/patterns/func_pencil_16_hov.png' and @title = ' Absence Type Bereavement Leave Hours 8  Start Date 13-04-2023 End Date 13-04-2023 Status Scheduled Edit' and @alt = ' Absence Type Bereavement Leave Hours 8  Start Date 13-04-2023 End Date 13-04-2023 Status Scheduled Edit']</value>
      <webElementGuid>ac6cab7e-1bd7-49e8-b550-f066792eb45f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
