<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Done</name>
   <tag></tag>
   <elementGuidId>94d505af-c5c9-4d75-bdc9-ba8079b570a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::*[name()='svg'][5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ad0e654b-4d8f-470a-a5a6-35197777c66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>53688542-e78c-415f-9627-ffd572b2fec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-bkgd03 xi6</value>
      <webElementGuid>fdffb164-07a6-486f-897a-3d0ace969c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 48 48</value>
      <webElementGuid>e1c4b116-a9ea-4101-9d65-e09f6ef5e1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:SPdonei::icon</value>
      <webElementGuid>e8c641d1-6ce4-4c82-8fe6-27c36845625c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3132f431-7af3-4ee5-86df-0690c2b4f22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>fff74f4e-a23f-42fb-aaa8-9ab98b0a738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afrsvg</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b0e0ad8-9b78-4388-ab44-92cd590c1bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>f5c783a3-0b4d-43f5-b8c5-cce862150ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:SPdonei::icon&quot;)</value>
      <webElementGuid>0eebcb11-3382-4b86-8869-0ae70dc35bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>b327ec5a-6905-4714-b222-ffe5ccd0ae12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SB'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7c6b7bf7-e865-4e87-9997-275cc8c38bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Existing Absences'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>dd09ace8-19c0-4f18-bc37-350dfbdf4432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = '_FOpt1:_FOr1:0:_FONSr2:0:MAnt2:0:r1:0:abHiUpl:UPsp1:SPdonei::icon' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>e38a6598-179e-4101-89ca-7f37050cf128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
